### PR TITLE
DM-46312: Migrate unit tests to ComCamSim data

### PR DESCRIPTION
**Pull request by kfindeisen**
This PR migrates the unit test repo from DECam to ComCamSim, and cleans up some related technical debt.

### CODE REVIEW

**Review by hsinfang — APPROVED** [review]
LGTM -- thanks for updating the test repo. 

`tests/data/make_central_repo.sh` seems missed in this update. I've found that file valuable in re-constructing or modifying the test repo, which we do need to do from time to time.

**Comment by kfindeisen** [comment]
Oops, so that's where `export.yaml` was used! I'll fix it.

**Comment by hsinfang** [comment]
Another comment: with this update, we no longer need `setupRequired(obs_decam)` in `ups/prompt_processing.table`, I think.

**Comment by kfindeisen** [comment]
@hsinfang would you like to take a look at `make_central_repo.sh`? I ended up almost completely rewriting it.

**Comment by hsinfang** [comment]
Looks great to me, and it will also serve as a good reference if later we want to build a new repo with another dataset. Thank you!

**Pull request merged**
